// lib/data.ts — all static data for Rakma Global

export interface PropertyStat {
  v: string
  k: string
}

export interface Property {
  id: string
  loc: string
  city: string
  address: string
  postalCode: string
  sub: string
  img: string
  stats: PropertyStat[]
  pct: number
  raised: string
  rem: string
  desc: string
  yield: number
  badge: 'open' | 'new' | 'hot' | 'closing'
  tags: string[]
  value: string
  investors: number
}

export const PROPERTIES: Property[] = [
  {
    id: 'mcpherson-88',
    loc: 'Caledon, ON · L7C 4A7',
    city: 'Caledon',
    address: '88 Mcpherson Rd',
    postalCode: 'L7C 4A7',
    sub: 'Single-family detached · Rental income property',
    img: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=900&q=80',
    stats: [
      { v: '8.2%', k: 'Yield p.a.' },
      { v: '$1.1M', k: 'Value' },
      { v: '487', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 58,
    raised: '$638K',
    rem: '$462K',
    desc: 'A premium single-family home in sought-after Caledon. Consistent rental income driven by families relocating to the area. Legally structured via Ontario SPV with monthly distributions.',
    yield: 8.2,
    badge: 'open',
    tags: ['all', 'open', 'caledon'],
    value: '$1.1M',
    investors: 487,
  },
  {
    id: 'mcpherson-90',
    loc: 'Caledon, ON · L7C 4A8',
    city: 'Caledon',
    address: '90 Mcpherson Rd',
    postalCode: 'L7C 4A8',
    sub: 'Single-family detached · Rental income property',
    img: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=900&q=80',
    stats: [
      { v: '8.3%', k: 'Yield p.a.' },
      { v: '$1.1M', k: 'Value' },
      { v: '423', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 61,
    raised: '$671K',
    rem: '$429K',
    desc: 'Adjacent to 88 Mcpherson with identical fundamentals. Ideal for investors seeking exposure to premium Caledon with strong rental demand and full SPV protection.',
    yield: 8.3,
    badge: 'open',
    tags: ['all', 'open', 'caledon'],
    value: '$1.1M',
    investors: 423,
  },
  {
    id: 'deer-ridge',
    loc: 'Caledon, ON · L7C 3Z7',
    city: 'Caledon',
    address: '14 Deer Ridge Trail',
    postalCode: 'L7C 3Z7',
    sub: 'Premium detached home · New listing',
    img: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=900&q=80',
    stats: [
      { v: '7.9%', k: 'Yield p.a.' },
      { v: '$1.3M', k: 'Value' },
      { v: '198', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 22,
    raised: '$286K',
    rem: '$1.014M',
    desc: "Newly listed premium detached home on one of Caledon's most desirable streets. Early investors benefit from maximum upside on this early-stage opportunity.",
    yield: 7.9,
    badge: 'new',
    tags: ['all', 'new', 'caledon'],
    value: '$1.3M',
    investors: 198,
  },
  {
    id: 'goswell-11',
    loc: 'Brampton, ON · L6P 3G8',
    city: 'Brampton',
    address: '11 Goswell St',
    postalCode: 'L6P 3G8',
    sub: 'Detached home · Brampton growth corridor',
    img: 'https://images.unsplash.com/photo-1584752242818-b4bd1f438a6b?w=900&q=80',
    stats: [
      { v: '7.8%', k: 'Yield p.a.' },
      { v: '$890K', k: 'Value' },
      { v: '312', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 32,
    raised: '$285K',
    rem: '$605K',
    desc: "Brampton is one of Canada's fastest-growing cities with a booming immigrant population driving sustained rental demand. Excellent location near transit.",
    yield: 7.8,
    badge: 'new',
    tags: ['all', 'new', 'brampton'],
    value: '$890K',
    investors: 312,
  },
  {
    id: 'purple-sage',
    loc: 'Brampton, ON · L4H 3N5',
    city: 'Brampton',
    address: '63 Purple Sage Dr',
    postalCode: 'L4H 3N5',
    sub: 'Detached home · Northwest Brampton',
    img: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=80',
    stats: [
      { v: '8.0%', k: 'Yield p.a.' },
      { v: '$920K', k: 'Value' },
      { v: '456', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 49,
    raised: '$451K',
    rem: '$469K',
    desc: 'Desirable family home in northwest Brampton near major transit and top-rated schools. High occupancy and strong rent rolls make this one of the most stable performers.',
    yield: 8.0,
    badge: 'open',
    tags: ['all', 'open', 'brampton'],
    value: '$920K',
    investors: 456,
  },
  {
    id: 'jura-25',
    loc: 'Brampton, ON · L6P 0H8',
    city: 'Brampton',
    address: '25 Jura Crescent',
    postalCode: 'L6P 0H8',
    sub: 'Detached home · Active rental income',
    img: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&q=80',
    stats: [
      { v: '8.4%', k: 'Yield p.a.' },
      { v: '$820K', k: 'Value' },
      { v: '342', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 74,
    raised: '$607K',
    rem: '$213K',
    desc: 'One of our top-performing Brampton properties with active rental income and a long-term tenant. Monthly distributions currently being paid to investors.',
    yield: 8.4,
    badge: 'open',
    tags: ['all', 'open', 'brampton'],
    value: '$820K',
    investors: 342,
  },
  {
    id: 'gore-9440',
    loc: 'Brampton, ON · L6P 4P9',
    city: 'Brampton',
    address: 'Unit 41, 9440 The Gore Rd',
    postalCode: 'L6P 4P9',
    sub: 'Townhouse unit · The Gore Road community',
    img: 'https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=900&q=80',
    stats: [
      { v: '8.1%', k: 'Yield p.a.' },
      { v: '$650K', k: 'Value' },
      { v: '278', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 41,
    raised: '$267K',
    rem: '$383K',
    desc: "Modern townhouse in one of Brampton's newest residential developments. Excellent access to Highway 427 and the Mount Pleasant GO station.",
    yield: 8.1,
    badge: 'open',
    tags: ['all', 'open', 'brampton'],
    value: '$650K',
    investors: 278,
  },
  {
    id: 'humberwood-700',
    loc: 'Etobicoke, ON · M9W 7J4',
    city: 'Etobicoke',
    address: '2018, 700 Humberwood Blvd',
    postalCode: 'M9W 7J4',
    sub: 'Condo unit · Toronto West access',
    img: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=900&q=80',
    stats: [
      { v: '7.6%', k: 'Yield p.a.' },
      { v: '$580K', k: 'Value' },
      { v: '145', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 17,
    raised: '$99K',
    rem: '$481K',
    desc: 'Etobicoke condo providing Toronto West access at a fraction of downtown prices. Strong rental demand from professionals near Pearson International Airport.',
    yield: 7.6,
    badge: 'new',
    tags: ['all', 'new', 'etobicoke'],
    value: '$580K',
    investors: 145,
  },
  {
    id: 'juneberry-151',
    loc: 'Thorold, ON · L2V 0H9',
    city: 'Thorold',
    address: '151 Juneberry Rd',
    postalCode: 'L2V 0H9',
    sub: 'Detached home · Niagara region',
    img: 'https://images.unsplash.com/photo-1598228723793-52759bba239c?w=900&q=80',
    stats: [
      { v: '8.7%', k: 'Yield p.a.' },
      { v: '$720K', k: 'Value' },
      { v: '389', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 67,
    raised: '$482K',
    rem: '$238K',
    desc: 'Thorold is one of the most undervalued markets in the Niagara region. Strong demand from Brock University students and Niagara Health System staff. Highest-yielding Ontario property.',
    yield: 8.7,
    badge: 'open',
    tags: ['all', 'open', 'thorold'],
    value: '$720K',
    investors: 389,
  },
  {
    id: 'essex-199',
    loc: 'Sarnia, ON · N7T 0C2',
    city: 'Sarnia',
    address: '199 Essex St',
    postalCode: 'N7T 0C2',
    sub: 'Residential property · Sarnia',
    img: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=900&q=80',
    stats: [
      { v: '9.1%', k: 'Yield p.a.' },
      { v: '$540K', k: 'Value' },
      { v: '876', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 91,
    raised: '$491K',
    rem: '$49K',
    desc: "9.1% yield driven by Sarnia's industrial economy. Consistent demand from chemical plant and refinery workers. 91% funded with very limited investment slots remaining.",
    yield: 9.1,
    badge: 'hot',
    tags: ['all', 'open', 'sarnia'],
    value: '$540K',
    investors: 876,
  },
  {
    id: 'essex-219',
    loc: 'Sarnia, ON · N7T 4S1',
    city: 'Sarnia',
    address: '219 Essex St',
    postalCode: 'N7T 4S1',
    sub: 'Residential property · Closing soon',
    img: 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=900&q=80',
    stats: [
      { v: '9.3%', k: 'Yield p.a.' },
      { v: '$520K', k: 'Value' },
      { v: '932', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 95,
    raised: '$494K',
    rem: '$26K',
    desc: 'Highest-yielding Sarnia property at 9.3%. Nearly fully funded with only $26K remaining. This is a final opportunity before closing.',
    yield: 9.3,
    badge: 'closing',
    tags: ['all', 'closing', 'sarnia'],
    value: '$520K',
    investors: 932,
  },
  {
    id: 'southbridge-52',
    loc: 'London, ON · N6L 0G8',
    city: 'London ON',
    address: 'Unit 52, 3635 Southbridge Ave',
    postalCode: 'N6L 0G8',
    sub: 'Condo townhouse · Southwest London',
    img: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=900&q=80',
    stats: [
      { v: '8.5%', k: 'Yield p.a.' },
      { v: '$610K', k: 'Value' },
      { v: '521', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 55,
    raised: '$336K',
    rem: '$274K',
    desc: 'Modern townhouse condo near Fanshawe College and Western University. Strong student and young professional rental demand makes this highly liquid.',
    yield: 8.5,
    badge: 'open',
    tags: ['all', 'open', 'london-on'],
    value: '$610K',
    investors: 521,
  },
  {
    id: 'southbridge-41',
    loc: 'London, ON · N6L 0G8',
    city: 'London ON',
    address: 'Unit 41, 3635 Southbridge Ave',
    postalCode: 'N6L 0G8',
    sub: 'Condo townhouse · Southwest London',
    img: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=900&q=80',
    stats: [
      { v: '8.4%', k: 'Yield p.a.' },
      { v: '$600K', k: 'Value' },
      { v: '478', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 48,
    raised: '$288K',
    rem: '$312K',
    desc: 'Sister unit to Unit 52 with nearly identical fundamentals. Ideal for investors wanting double exposure to the London Ontario market.',
    yield: 8.4,
    badge: 'open',
    tags: ['all', 'open', 'london-on'],
    value: '$600K',
    investors: 478,
  },
  {
    id: 'christina-145',
    loc: 'Sarnia, ON · N7T 8H4',
    city: 'Sarnia',
    address: '145 Christina St N.',
    postalCode: 'N7T 8H4',
    sub: 'Newly listed · Sarnia downtown',
    img: 'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=900&q=80',
    stats: [
      { v: '9.0%', k: 'Yield p.a.' },
      { v: '$490K', k: 'Value' },
      { v: '87', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 9,
    raised: '$44K',
    rem: '$446K',
    desc: "Brand new to portfolio at just 9% funded. Christina Street is Sarnia's main commercial corridor. Early investors have maximum upside on capital appreciation.",
    yield: 9.0,
    badge: 'new',
    tags: ['all', 'new', 'sarnia'],
    value: '$490K',
    investors: 87,
  },
  {
    id: 'watergarden-15',
    loc: 'Mississauga, ON · L5B 1B2',
    city: 'Mississauga',
    address: 'Suite 1009, 15 Watergarden Dr',
    postalCode: 'L5B 1B2',
    sub: 'High-rise condo · Mississauga city centre',
    img: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=900&q=80',
    stats: [
      { v: '8.8%', k: 'Yield p.a.' },
      { v: '$670K', k: 'Value' },
      { v: '634', k: 'Investors' },
      { v: '5 yrs', k: 'Hold' },
    ],
    pct: 72,
    raised: '$482K',
    rem: '$188K',
    desc: 'Premium 10th-floor suite steps from Square One and the Hurontario LRT. One of the strongest rental markets in the GTA outside Toronto proper.',
    yield: 8.8,
    badge: 'open',
    tags: ['all', 'open', 'mississauga'],
    value: '$670K',
    investors: 634,
  },
]

export const TICKER_ITEMS = [
  { address: '88 Mcpherson Rd, Caledon ON', label: 'Active income' },
  { address: '90 Mcpherson Rd, Caledon ON', label: 'Active income' },
  { address: '25 Jura Crescent, Brampton ON', label: '74% funded' },
  { address: '199 Essex St, Sarnia ON', label: '91% funded' },
  { address: '219 Essex St, Sarnia ON', label: 'Closing soon' },
  { address: '15 Watergarden Dr, Mississauga ON', label: '72% funded' },
  { address: '3635 Southbridge Ave, London ON', label: 'Active income' },
  { address: '151 Juneberry Rd, Thorold ON', label: '8.7% yield' },
]

export const TESTIMONIALS = [
  {
    initials: 'AR',
    name: 'Ahmed R.',
    location: 'Cairo, Egypt',
    invested: '$2,400',
    text: 'I never imagined owning Canadian property from abroad. Rakma made it happen for $500. I now collect monthly rental income on three properties. Absolute game changer.',
  },
  {
    initials: 'SN',
    name: 'Sara N.',
    location: 'Karachi, Pakistan',
    invested: '$800',
    text: 'As a young professional in Karachi, property felt decades away. With Rakma I started at $100 and now receive consistent monthly passive income. Truly life-changing.',
  },
  {
    initials: 'MA',
    name: 'Mohammed A.',
    location: 'Dubai, UAE',
    invested: '$15,000',
    text: 'The transparency is what got me. Every fee and document visible before I commit a cent. The platform is beautiful and the returns are very, very real.',
  },
]

export const INSIGHTS = [
  {
    category: 'Market insight',
    title: 'Why Canadian residential real estate remains the safest long-term investment in 2025',
    excerpt:
      "Canada's combination of strong immigration targets, housing shortage, and stable governance creates rental demand unlike anywhere else in the G7.",
    date: 'May 2025',
  },
  {
    category: 'Platform update',
    title: 'Rakma Global crosses $10M in assets under management',
    excerpt:
      'Our first major milestone. 5,000 investors across 34 countries, all earning from Canadian real estate.',
    date: 'April 2025',
  },
  {
    category: "Founder's note",
    title: "The immigrant mindset is the world's most underrated investment advantage",
    excerpt:
      "Rakesh Sharma on why people who started with nothing often build more wealth than those who started with everything.",
    date: 'March 2025',
  },
]

export const WHY_ITEMS = [
  {
    num: '01',
    icon: '◈',
    title: 'No minimum barrier',
    desc: 'Start with $100. Real estate used to be for the wealthy few. Rakma Global changes that — anyone, anywhere, can own premium property today.',
  },
  {
    num: '02',
    icon: '⬡',
    title: 'Legally structured',
    desc: 'Every property is held in a legally structured Special Purpose Vehicle (SPV). Your shares are registered, binding, and backed by real assets.',
  },
  {
    num: '03',
    icon: '◎',
    title: 'Monthly income',
    desc: 'Earn your share of rental income every month, automatically. Funds distribute to your Rakma wallet — no paperwork, no delays.',
  },
  {
    num: '04',
    icon: '⟡',
    title: 'Global diversification',
    desc: 'Spread risk across 50+ cities and multiple currencies. Canada, Dubai, London, Istanbul, Singapore — from one unified dashboard.',
  },
  {
    num: '05',
    icon: '⬢',
    title: 'Full transparency',
    desc: 'See every fee, document, and projection before investing. Real-time tracking and quarterly reports included on every property.',
  },
  {
    num: '06',
    icon: '◇',
    title: 'Exit when you want',
    desc: 'List your shares on our secondary marketplace. Most positions sell within 30–60 days. Your investment works for you.',
  },
]
